CREATE PROC FI_SP_ConsBenef
    @ID            BIGINT,
	@IDCLIENTE     BIGINT
AS
BEGIN
	IF(ISNULL(@ID, 0) = 0)
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WHERE IDCLIENTE = @IDCLIENTE;
	ELSE
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WHERE ID = @ID;
END